version: "3.9"

services:
  mcp-openai-router:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-openai-router
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000" # только внутри сети
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ./:/app:ro
    networks:
      - mcp-net

networks:
  mcp-net:
    external: true
