services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080" # внешний 8080 → внутренний 8080
    volumes:
      - ./:/app:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
