version: "3.9"

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${MCP_OPENAI_ROUTER_ENDPOINT}
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "${PORT}"
    volumes:
      - ./:/app:rw
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:${PORT}/health
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      default:
      mcp-net:
        aliases:
          - ${MCP_OPENAI_ROUTER_ENDPOINT}

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
      - ACME_EMAIL=${ACME_EMAIL}
    networks:
      default:
      mcp-net:

volumes:
  caddy_data:
  caddy_config:

networks:
  mcp-net:
    external: true
